package com.tripmate.entity;

public interface ConstCode {
    String JOIN_CHANNEL_CODE = "MB001";
    String JOIN_CHANNEL_CODE_TRIPMATE = "10";
    String JOIN_CHANNEL_CODE_KAKAO = "20";
    String JOIN_CHANNEL_CODE_NAVER = "30";

    String MEMBER_STATUS_CODE = "MB002";
    String MEMBER_STATUS_CODE_COMPLETE = "10";
    String MEMBER_STATUS_CODE_TEMPORARY = "20";
    String MEMBER_STATUS_CODE_WITHDRAW = "30";
    String MEMBER_STATUS_CODE_ISSUE_TEMPORARY_PASSWORD = "40";

    String GENDER_CODE = "MB003";
    String GENDER_CODE_MALE = "10";
    String GENDER_CODE_FEMALE = "20";

    String EMAIL_TYPE_CODE = "MB004";
    String EMAIL_TYPE_CODE_JOIN = "10";
    String EMAIL_TYPE_CODE_EMAIL_CHANGE = "20";
    String EMAIL_TYPE_CODE_TEMPORARY_PASSWORD = "30";

    String DUPLICATION_CHECK_CODE = "MB005";
    String DUPLICATION_CHECK_MEMBER_ID = "10";
    String DUPLICATION_CHECK_NICK_NAME = "20";
    String DUPLICATION_CHECK_EMAIL = "30";

    String POST_TYPE_CODE = "CT001";
    String POST_TYPE_CODE_LODGING = "10";

    String ATTRIBUTE_TYPE_CODE = "CT003";
    String ATTRIBUTE_TYPE_CODE_HASHTAG = "10";
    String ATTRIBUTE_TYPE_CODE_TRIP_THEME = "20";

    String MEMBER_SEARCH_DIVI_CODE = "MB006";
    String MEMBER_SEARCH_DIVI_CODE_ID = "10";
    String MEMBER_SEARCH_DIVI_CODE_NICK_NAME = "20";
    String MEMBER_SEARCH_DIVI_CODE_EMAIL = "30";

    String INVITE_TYPE_CODE = "CT0006";
    String INVITE_TYPE_CODE_MEMBER = "10";
    String INVITE_TYPE_CODE_NONMEMBER = "20";
}